language: php

php:
  - 5.6.18
  - 7.0
  - 7.1
  - 7.2

# faster builds on new travis setup not using super user
sudo: false

# matrix
matrix:
  allow_failures:
    - php: 7.2

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit
