language: php

php:
  - 5.6.18
  - 7.0
  - 7.1

# faster builds on new travis setup not using super user
sudo: false

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --verbose
